{
 "title": "Search Trends",
 "tags": [ "search-trends" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Incoming events per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(search_events_received_total[1m])"
    }
   ]
  },
  {
   "title": "Top requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(search_top_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Events in current window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "search_window_events" }
   ]
  },
  {
   "title": "Rejected events per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(search_events_abuse_total[1m])"
    },
    {
     "expr": "rate(search_events_stopword_total[1m])"
    },
    {
     "expr": "rate(search_bad_messages_total[1m])"
    }
   ]
  }
 ]
}